# Generated by Django 5.1.1 on 2024-09-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Carnet', models.CharField(max_length=20, unique=True)),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('CUI', models.CharField(max_length=13, unique=True)),
                ('Telefono', models.CharField(max_length=15)),
                ('Correo', models.EmailField(max_length=254, unique=True)),
                ('Genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=10)),
                ('Estado_Civil', models.CharField(choices=[('s', 'Soltero'), ('c', 'Casado')], max_length=10)),
                ('Fecha_de_Nacimiento', models.DateField()),
            ],
        ),
    ]
